version: '3.7'

volumes:
  pti-health-d2b:

networks:
  pti-health-net:

services:
  db:
    image: postgres:11
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      TZ: America/Asuncion
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak-test}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
    networks:
      pti-health-net:
        aliases:
         - db
    ports:
      - 5432:5432
    volumes:
      - pti-health-d2b:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:10.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak-test
      KEYCLOAK_USER: ${KEYCLOAK_USER:-ptihealth}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-test}
      TZ: America/Asuncion
    restart: unless-stopped
    command: ["-Dkeycloak.profile.feature.account_api=enabled", "-Dkeycloak.profile.feature.upload_scripts=enabled", "-Dkeycloak.profile.feature.scripts=enabled", "-b", "0.0.0.0"]
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./themes/base-CMR:/opt/jboss/keycloak/themes/base-CMR
    networks:
      pti-health-net:
        aliases:
         - kc
